name: n8n-client-go CI/CD

on:
  pull_request:
    branches: [main]

jobs:
  format-and-test:
    name: Formatting and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Run gofmt
        run: |
          FMT_RESULT=$(gofmt -l .)
          if [ -n "$FMT_RESULT" ]; then
            echo "The following files are not properly formatted:"
            echo "$FMT_RESULT"
            exit 1
          fi

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          fail_ci_if_error: true

      - name: Build
        run: go build -v ./...
